---
title: "ESM 204 HW4: A Climate Change Model"
author: "Cameryn Brock and Allison Hacker"
date: "5/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
```

```{r, echo = FALSE}
library(tidyverse)
```

## 1. Plots

### a) Temperature over time

```{r}
years <- data.frame(
  year = seq(from = 0, to = 200, by = 1))

# temperature function
temp_fun = function(t, T){
  temp = pmin(t*T/100,T)
  }

temp_time <- years %>% 
  mutate(none = temp_fun(t = year, T = 0),
         moderate = temp_fun(t = year, T = 2),
         extreme = temp_fun(t = year, T = 8)) %>% 
  pivot_longer(2:4,
               values_to = "temp",
               names_to = "climate_change")
```


```{r, echo = FALSE}
ggplot(temp_time, aes(x = year,
                      y = temp,
                      color = climate_change)) +
  geom_line(show.legend = FALSE) + 
  scale_color_manual(values = c("indianred", "goldenrod", "cadetblue")) +
  theme_minimal() + 
  theme(plot.margin = unit(c(1, 4, 1, 1), "lines")) +
  coord_cartesian(clip = "off") +
  geom_label(x = 201, y = 8, size = 3, 
             hjust = 0, label.size = 0,
             label = "Extreme Climate \nChange (CC)",
             color = "indianred") +
  geom_label(x = 201, y = 2, size = 3, 
             hjust = 0, label.size = 0,
             label = "Moderate CC",
             color = "goldenrod") +
  geom_label(x = 201, y = 0, size = 3, 
             hjust = 0, label.size = 0,
             label = "No CC",
             color = "cadetblue") +
  labs(x = "Year",
       y = "Temperature",
       color = "Climate Change \nScenario")
```

### b) Consumption over time

```{r}
# economic activity retained function
econ_fun <- function(temp, B = 0.05){
  econ = exp(-B*temp^2)
  }

econ_time <- temp_time %>% 
  mutate(econ = econ_fun(temp = temp))

ggplot(econ_time, aes(x = year,
                      y = econ,
                      color = climate_change)) + 
  geom_line()

# total consumption function
consum_fun <- function(econ, g = 0.01, t){
  consum = econ*exp(g*t)
  }  

consum_time <- econ_time %>% 
  mutate(consum = consum_fun(t = year, econ = econ))
```


```{r, echo = FALSE}
ggplot(consum_time, aes(x = year,
                      y = consum,
                      color = climate_change)) +
  geom_line(show.legend = FALSE) + 
  scale_color_manual(values = c("indianred", "goldenrod", "cadetblue")) +
  theme_minimal() + 
  theme(plot.margin = unit(c(1, 4, 1, 1), "lines")) +
  coord_cartesian(clip = "off") +
  geom_label(x = 201, y = 0.35, size = 3, 
             hjust = 0, label.size = 0,
             label = "Extreme CC",
             color = "indianred") +
  geom_label(x = 201, y = 6.05, size = 3, 
             hjust = 0, label.size = 0,
             label = "Moderate CC",
             color = "goldenrod") +
  geom_label(x = 201, y = 7.4, size = 3, 
             hjust = 0, label.size = 0, 
             label = "No Climate \nChange (CC)",
             color = "cadetblue") +
  labs(x = "Year",
       y = "Total Consumption",
       color = "Climate Change \nScenario")
```

### c) Undiscounted utility over time

```{r}
# society utility function
utility_fun <- function(C, n = 0.5){
  utility = ((C^(1-n))/(1-n))
  }

utility_time <- consum_time %>% 
  mutate(utility = utility_fun(C = consum))
```

```{r, echo = FALSE}
ggplot(utility_time, aes(x = year,
                      y = utility,
                      color = climate_change)) +
  geom_line(show.legend = FALSE) + 
  scale_color_manual(values = c("indianred", "goldenrod", "cadetblue")) +
  theme_minimal() + 
  theme(plot.margin = unit(c(1, 4, 1, 1), "lines")) +
  coord_cartesian(clip = "off") +
  geom_label(x = 201, y = 1.1, size = 3, 
             hjust = 0, label.size = 0,
             label = "Extreme CC",
             color = "indianred") +
  geom_label(x = 201, y = 4.9, size = 3, 
             hjust = 0, label.size = 0, 
             label = "Moderate CC", 
             color = "goldenrod") +
  geom_label(x = 201, y = 5.45, size = 3, 
             hjust = 0, label.size = 0,
             label = "No Climate \nChange (CC)", 
             color = "cadetblue") +
  scale_y_continuous(limits = c(0, 6)) +
  labs(x = "Year",
       y = "Undiscounted Utility",
       color = "Climate Change \nScenario")
```

## 2. Analysis

### a) 

```{r}
# discount rate function
disc_fun <- function(y = 0.005, n = 0.5, g = 0.01){
  disc = y + n*g
  }



```

### b) 

```{r}

```

### c)

```{r, include = FALSE}
library(patchwork)

c_4.4 <- years %>% 
  mutate(temp = temp_fun(t = year, T = 4.4),
         econ = econ_fun(temp = temp),
         consum = consum_fun(t = year, econ = econ),
         utility = utility_fun(C = consum))

c_0 <- years %>% 
  mutate(temp = temp_fun(t = year, T = 0),
         econ = econ_fun(temp = temp),
         consum = consum_fun(t = year, econ = econ),
         utility = utility_fun(C = consum))

c_temp_g <- ggplot() + 
  geom_line(data = c_4.4, aes(x = year, y = temp),
            color = "red") + 
  geom_line(data = c_0, aes(x = year, y = temp),
            color = "blue")

c_econ_g <- ggplot() + 
  geom_line(data = c_4.4, aes(x = year, y = econ),
            color = "red") +
  geom_line(data = c_0, aes(x = year, y = econ),
            color = "blue")

c_consum_g <- ggplot() + 
  geom_line(data = c_4.4, aes(x = year, y = consum),
            color = "red") + 
  geom_line(data = c_0, aes(x = year, y = consum),
            color = "blue")

c_utility_g <- ggplot() + 
  geom_line(data = c_4.4, aes(x = year, y = utility),
            color = "red") + 
  geom_line(data = c_0, aes(x = year, y = utility),
            color = "blue")

(c_temp_g + c_econ_g) / (c_consum_g + c_utility_g)
  
```

