---
title: "ESM204 Homework 4"
author: "Allison Hacker and Cameryn Brock"
date: "5/20/2020"
output: html_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, include=FALSE}
library(tidyverse)
```


### Equations and Plots
```{r}
# temperature

#define variables
sims = 201
temps <- rep(NA, sims)
temps_0 <- rep(NA, sims)
temps_2 <- rep(NA, sims)
temps_8 <- rep(NA, sims)
t <- seq(from = 0, to = 200, by = 1)

# temperature function
temp_fun<- function(T, x){
  temp = min((T*x)/100, T)
}

# create temp vectors for CC scenarios
for(i in 1:sims){
  temps_0[i] <- temp_fun(0, i-1)
}

for(i in 1:sims){
  temps_2[i] <- temp_fun(2, i-1)
}

for(i in 1:sims){
  temps_8[i] <- temp_fun(8, i-1)
}

# combine into dataframe
temps_data_raw <- data.frame(t, temps_0, temps_2, temps_8)
temps_data <- temps_data_raw %>% 
  pivot_longer(cols = starts_with("temps"), names_to = "cc_scenario", values_to = "temp")

# plot temps
ggplot(data = temps_data, aes(x = t, 
                              y = temp, 
                              color = cc_scenario))+
  geom_line()

```


```{r}
# economic activity
K <- rep(NA, sims)
K_0<- rep(NA, sims)
K_2<- rep(NA, sims)
K_8<- rep(NA, sims)

B = 0.05

econ_fun <- function(temp, B = 0.05){
  K = exp(-B*temp^2)
}

for(i in 1:sims){
   K_0[i] <- econ_fun(temps_0[i])
}

for(i in 1:sims){
   K_2[i] <- econ_fun(temps_2[i])
}

for(i in 1:sims){
   K_8[i] <- econ_fun(temps_8[i])
}

```

```{r}
# consumption
C <- rep(NA, sims)
C_0<- rep(NA, sims)
C_2<- rep(NA, sims)
C_8<- rep(NA, sims)

con_fun <- function(K, x, g = 0.01){
  C = K*exp(g*x)
}

 for(i in 0:sims){
   C_0[i] <- con_fun(K_0[i], i-1)
 }

for(i in 0:sims){
   C_2[i] <- con_fun(K_2[i], i-1)
}

for(i in 0:sims){
   C_8[i] <- con_fun(K_8[i], i-1)
}

# combine into dataframe
con_data_raw <- data.frame(t, C_0, C_2, C_8)
con_data <- con_data_raw %>% 
  pivot_longer(cols = starts_with("C"), names_to = "cc_scenario", values_to = "C")

# plot K
ggplot(data = con_data, aes(x = t, y = C, color = cc_scenario))+
  geom_line()
```

```{r}
# Utility
U <- rep(NA, sims)
U_0<- rep(NA, sims)
U_2<- rep(NA, sims)
U_8<- rep(NA, sims)

u_fun <- function(C,n = 0.5){
  U = (C^(1-n))/(1-n)
}

for(i in 0:sims){
   U_0[i] <- u_fun(C_0[i])
}

for(i in 0:sims){
   U_2[i] <- u_fun(C_2[i])
}

for(i in 0:sims){
   U_8[i] <- u_fun(C_8[i])
}

```

```{r}
# Discounting
d = 0.005
n = 0.5
g = 0.01

r_fun <- function(d = 0.005, n = 0.5, g = 0.01){
  r = d + n*g
}

discount <- function(U, r){
  pv <- rep(NA, sims)
  for(i in 1:sims){
    pv[i] = U[i]/(1+r)^(i-1)
  }
  pv_total = sum(pv)
  return(pv_total)
}
```

### Analysis

##### Part A
```{r}
# Function for loss in present value of utility

loss_fun <- function(T, B = 0.05, d=0.005, n = 0.5, g=0.01){
# Climate Change
  for(i in 1:sims){
  temps[i] <- temp_fun(T, i-1)}

for(i in 1:sims){
  K[i] <- econ_fun(temps[i], B = B)}

for(i in 1:sims){
  C[i] <- con_fun(K[i], i-1)}

for(i in 1:sims){
  U[i] <- u_fun(C[i])}

r <- r_fun(d = d, n = n, g = g)
cc_utility <- discount(U, r)

# No climate change
T <- 0

for(i in 1:sims){
  temps[i] <- temp_fun(T, i-1)}

for(i in 1:sims){
  K[i] <- econ_fun(temps[i])}

for(i in 1:sims){
  C[i] <- con_fun(K[i], i-1)}

for(i in 1:sims){
  U[i] <- u_fun(C[i])}

utility <- discount(U, r)

L <- p_change(L0 = utility, L_new = cc_utility)
return(L)
}

L_test <- loss_fun(T = 4.4)
```


##### Part B
```{r}

p_change <- function(L0, L_new){
  pc <- (L_new-L0)/L0
  return(pc*100)
}

T <- 4.4
T10 <- T*1.1
B10 <- B*1.1
n10 <- n*1.1
g10 <- g*1.1

r_n <- r_fun(n = n10)
r_g <- r_fun(g = g10)

L_T <- loss_fun(T = T10)
L_B <- loss_fun(T = 4.4, B = B10)
L_n <- loss_fun(T = 4.4, n = n10)
L_g <- loss_fun(T = 4.4, g = g10)

```

```{r}
# what fraction of consumption would society be willing to "pay" every year for 200 years to completely prevent climate change?
dis <- rep(NA, sims)
dif <- U_0-U_8
dif_sum <- sum(dif)
sum(U_0)
r <- r_fun()
dis <- discount(dif, r)

u_fun_con<- function(C, x, n = 0.5){
  U = ((C*(1-x))^(1-n))/(1-n)
}



```

